version: '3.8'

services:
  shorts-generator:
    build: .
    container_name: shorts-generator
    ports:
      - "7860:7860"
    volumes:
      - ./output:/app/output
      - quotes_data:/app/data/quotes
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - shorts-network
    mem_limit: 2g
    cpus: '1.0'

volumes:
  quotes_data:
    name: shorts_generator_quotes_data
    external: false

networks:
  shorts-network:
    driver: bridge
    name: shorts-generator-network