name: Simple Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Simple test
      run: |
        echo "✅ Actions is working!"
        echo "Branch: ${{ github.ref }}"
        echo "Repository: ${{ github.repository }}"
EOF